name: Iris Pipeline CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]
permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Create report folder
      run: mkdir -p reports

    - name: Run tests (tolerate failure)
      run: |
        pytest tests/ > reports/output.txt || echo "Tests failed"

    - name: Install CML
      run: npm install -g @dvcorg/cml

    - name: Post test report via CML
      if: always()
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Test Results 📋" > comment.md
        cat reports/output.txt >> comment.md
        cml comment create comment.md
