name: Iris Pipeline CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and save report
      run: |
        mkdir -p reports
        pytest tests/ > reports/output.txt

    - name: Install Node.js for CML
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install CML
      run: npm install -g @dvcorg/cml

    - name: Post CML Comment with Test Report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Test Results 📋" > comment.md
        cat reports/output.txt >> comment.md
        cml comment create comment.md
